version: '3.7'

services:
  app:
    platform: linux/amd64
    image: 'vending:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vending
    ports:
      - "8181:8181"
    depends_on:
      - db
    environment:
      - SERVER_PORT= 8181
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.postgresql.Driver

  db:
    platform: linux/amd64
    image: 'postgres:13.1-alpine'
    container_name: db
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=